### ISSUE TITLE
BSD diff tool causes 5 errors in test suite

### ISSUE THREAD

**Issue by yzgyyang** [yzgyyang/diffoscope#3]
Due to the different behaviors between GNU diff and BSD diff, test suites will fail on ~5 cases when running on FreeBSD.

**Comment by yzgyyang** [comment]
~~@emaste Here's a simple patch to force diffoscope to use `gdiff`on FreeBSD. We should add `textproc/diffutils` to the dependency list as well.
[diffoscope_gdiff_patch.diff.txt](https://github.com/yzgyyang/diffoscope/files/1180866/diffoscope_gdiff_patch.diff.txt)~~

~~Commit:
https://github.com/yzgyyang/diffoscope/commit/0f9f205ddbc7e7624c746d26e7daf3633fbbff54~~

**Comment by yzgyyang** [comment]
Note that there are:
```python
@tool_required('diff')
```
everywhere across the project, I didn't bother to change every one of them but to assume that the system will have `diff` and `gdiff` at the same time. Is that a bit too tricky?

**Comment by yzgyyang** [comment]
@mapreri This patch is to let diffoscope use `gdiff` if available. We will make `gdiff` a dependency of diffoscope in FreeBSD Ports.
[diffoscope_gdiff_patch.diff.txt](https://github.com/yzgyyang/diffoscope/files/1191467/diffoscope_gdiff_patch.diff.txt)


Commit:
https://github.com/yzgyyang/diffoscope/commit/8a558c92d914ea6678d7aedc6dafe3bcca7dcb56

**Comment by mapreri** [comment]
that looks harmless, but I don't particularly like it: it doesn't convey enough "cleanness" on the implementation to me.
Could you please try to forward it to diffoscope@lists.reproducible-builds.org (or a new bug) so that others could comment on it and propose something nicer/tidier?

Also see https://bugs.debian.org/869868#13 for something vaguely related.

**Comment by yzgyyang** [comment]
> Could you please try to forward it to diffoscope@lists.reproducible-builds.org (or a new bug) so that others could comment on it and propose something nicer/tidier?

Will do. And will report it to the Debian bug tracker.

> Also see https://bugs.debian.org/869868#13 for something vaguely related.

This is interesting, and in fact we had some discussions about the ability to set tools used via some kind of configurations. However, it seems to me that it might be more effort than it's worth. See https://bugs.freebsd.org/bugzilla/show_bug.cgi?id=220870#c13 and the following comments.

@mapreri @emaste

**Comment by yzgyyang** [comment]
This issue was reported at https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=871029.

It is resolved by commits:
https://github.com/yzgyyang/diffoscope/commit/1de693d11d0d08d2127b40c6e7f3265f7ba9ab34
https://github.com/yzgyyang/diffoscope/commit/f8d8a742925a353fccd689fc75a4df2e3032d6b8
https://github.com/yzgyyang/diffoscope/commit/54d4bb1a70eae6798fd1c1d921ddbdb5eb0bd7c4
https://github.com/yzgyyang/diffoscope/commit/978dd1cfe490d276097aa35405d6d78986e533e4
